/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.26
 * Generated at: 2015-07-05 23:53:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.AirTraffic.Team2.Models.BookingBean;
import com.AirTraffic.Team2.Models.FlightBean;
import com.AirTraffic.Team2.Models.LocationBean;
import java.util.List;
import java.util.ArrayList;
import com.AirTraffic.Team2.Servlets.BookFlightServlet;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Element;
import java.io.FileOutputStream;

public final class BookFlight_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      com.AirTraffic.Team2.Models.BookingBean booking = null;
      booking = (com.AirTraffic.Team2.Models.BookingBean) _jspx_page_context.getAttribute("booking", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (booking == null){
        booking = new com.AirTraffic.Team2.Models.BookingBean();
        _jspx_page_context.setAttribute("booking", booking, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<title>AirTraffic</title>\n");
      out.write("<link\n");
      out.write("\thref=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/ui-lightness/jquery-ui.css\"\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<script\n");
      out.write("\tsrc=\"http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- <script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script> -->\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("$(document).ready(function() {\n");
      out.write("\t$(\"#dateOfBirth\").datepicker({\n");
      out.write("\t\tdateFormat : \"yy-mm-dd\"\n");
      out.write("\t});\t\t\n");
      out.write("});\n");
      out.write("function yesnoCheck() {\n");
      out.write("    if (document.getElementById('newCheck').checked) {\n");
      out.write("        document.getElementById('ifNew').style.display = 'block';\n");
      out.write("        document.getElementById('ifExisting').style.display = 'none';\n");
      out.write("    }\n");
      out.write("    else {\n");
      out.write("    \tdocument.getElementById('ifNew').style.display = 'none';\n");
      out.write("    \tdocument.getElementById('ifExisting').style.display = 'block';\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<a href=\"index.html\">Home Page</a>\n");
      out.write(" <br>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<form method=\"post\" action=\"booking\">\n");
      out.write("\t\tNew Customer<input type=\"radio\" onclick=\"javascript:yesnoCheck();\" name=\"yesno\" id=\"newCheck\"> \n");
      out.write("        Existing Customer <input type=\"radio\" checked=\"checked\" onclick=\"javascript:yesnoCheck();\" name=\"yesno\" id=\"existingCheck\"><br>\n");
      out.write("    <div id=\"ifNew\" style=\"display:none\">\n");
      out.write("        First Name <input type='text' id='fname' name='firstName'><br>\n");
      out.write("        Last Name  <input type='text' id='lname' name='lastName'>\n");
      out.write("        Gender <select name=\"genderDdl\">\t\t\t\t\n");
      out.write("\t\t\t\t<option value=\"Male\">Male</option>\n");
      out.write("\t\t\t\t<option value=\"Female\">Female</option>\t\t\t\t\n");
      out.write("\t\t\t    </select>\n");
      out.write("\t    Customer ID<input type='text' id='newCustID' name='newCustomerID'><br> \n");
      out.write("\t    ID Type <select name=\"idTypeDdl\">\t\t\t\t\n");
      out.write("\t\t\t\t<option value=\"PASSPORT\">PASSPORT</option>\n");
      out.write("\t\t\t\t<option value=\"DRIVING LICENCE\">DRIVING LICENCE</option>\t\n");
      out.write("\t\t\t\t<option value=\"Other\">Other</option>\t\t\t\n");
      out.write("\t\t\t    </select>\n");
      out.write("\t    Date of Birth <input type='text' id='dateOfBirth' name='dob'><br>\n");
      out.write("        Mobile<input type='text' id='custMobile' name='custMobile'>\n");
      out.write("        Email<input type='text' id='custEmail' name='custEmail'>\n");
      out.write("        Telephone<input type='text' id='custTelephone' name='custTelephone'>\n");
      out.write("        Address Line 1 <input type='text' id='custAdl1' name='custAdl1'>\n");
      out.write("        Address Line 2 <input type='text' id='custAdl2' name='custAdl2'>\n");
      out.write("        City <input type='text' id='custCity' name='custCity'>\n");
      out.write("        State  <input type='text' id='custState' name='custState'>\n");
      out.write("        Zipcode <input type='text' id='custZipcode' name='custZipcode'>\n");
      out.write("        Country <input type='text' id='custCountry' name='custCountry'>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div id=\"ifExisting\" style=\"display:block\">   \n");
      out.write("        Customer ID<input type='text' id='existingCustID' name='existingCustomerID'><br> \n");
      out.write("        <input type=\"submit\" value=\"View My Data\">             \n");
      out.write("\t\t<h1 align=\"center\">Booking Information Details</h1>\n");
      out.write("\t\t<table width=\"600\" height=\"300\" align=center cellspacing=0 border=\"0\"\n");
      out.write("\t\t\tcellpadding=0>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t<fieldset id=\"fieldhead\">\n");
      out.write("\t\t\t\t\t\t<legend>Booking Information</legend>\n");
      out.write("\t\t\t\t\t\t<BR>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<table align=center cellspacing=1 cellpadding=3>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div align=\"center\">\n");
      out.write("\t\t\t\t\t\t\t\t<table border=\"1\" cellpadding=\"5\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<caption>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h2>Details of Booking</h2>\n");
      out.write("\t\t\t\t\t\t\t\t\t</caption>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										if (request.getAttribute("error") != null) {
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>No Flight Found</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(request.getAttribute("error"));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										} 
									else {
										if (request.getAttribute("personDetails") != null
												&& !request.getAttribute("personDetails").equals("")) {
											
											List<FlightBean> flightList = (ArrayList<FlightBean>) request
													.getAttribute("flights");
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>First Name</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Last Name</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Gender</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Unique Id</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Id Type</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>DOB</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Mobile</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Email</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Telephone</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Address Line 1</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Address Line 2</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>City</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>State</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Zip code</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Country</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									
										List<BookingBean> bookPersonDetails = (ArrayList<BookingBean>) request
														.getAttribute("personDetails");

												for (int i = 0; i < bookPersonDetails.size(); i++) {
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(bookPersonDetails.get(i).getPersonBean().getPerson_fname());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(bookPersonDetails.get(i).getPersonBean().getPerson_lname());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(bookPersonDetails.get(i).getPersonBean().getPerson_gender());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(bookPersonDetails.get(i).getPersonBean().getPerson_official_id());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(bookPersonDetails.get(i).getPersonBean().getPerosn_official_id_type());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(bookPersonDetails.get(i).getPersonBean().getPerson_dob());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(bookPersonDetails.get(i).getPersonBean().getPerson_mobile());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(bookPersonDetails.get(i).getPersonBean().getPerson_email());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(bookPersonDetails.get(i).getPersonBean().getPerson_telephone());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(bookPersonDetails.get(i).getLocationBean().getLocation_line_1());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(bookPersonDetails.get(i).getLocationBean().getLocation_line_2());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(bookPersonDetails.get(i).getLocationBean().getCity());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(bookPersonDetails.get(i).getLocationBean().getState());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(bookPersonDetails.get(i).getLocationBean().getZipcode());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(bookPersonDetails.get(i).getLocationBean().getCountry());
      out.write("</td>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}				
							
									}
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</table>\n");
      out.write("\n");
      out.write("\t\t<br>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<table width=\"600\" height=\"300\" align=center cellspacing=0 border=\"0\"\n");
      out.write("\t\t\tcellpadding=0>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t<fieldset id=\"fieldhead\">\n");
      out.write("\t\t\t\t\t\t<legend>Flight Information</legend>\n");
      out.write("\t\t\t\t\t\t<BR>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<table align=center cellspacing=1 cellpadding=3>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div align=\"center\">\n");
      out.write("\t\t\t\t\t\t\t\t<table border=\"1\" cellpadding=\"5\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<caption>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h2>Flight Details</h2>\n");
      out.write("\t\t\t\t\t\t\t\t\t</caption>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										if (request.getAttribute("error") != null) {
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>No Flight Found</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(request.getAttribute("error"));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										} 
									else {
									
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Flight Name</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Departure Time</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Arrival Time</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Departure Airport</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Arrival Airport</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Departure Date</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Arrival Date</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									
										List<FlightBean> flightList = (List<FlightBean> )session.getAttribute("flight");

												for (int i = 0; i < flightList.size(); i++) {
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(flightList.get(i).getFlight_Id());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(flightList.get(i)
								.getFlight_scheduled_departure_time());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(flightList.get(i)
								.getFlight_scheduled_arrival_time());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(flightList.get(i).getFlightSegmentBean()
								.getOriginAirport().getAirport_iata());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(flightList.get(i).getFlightSegmentBean()
								.getDestinationAirport().getAirport_iata());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(flightList.get(i).getDepartureDate());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(flightList.get(i).getArrivalDate());
      out.write("</td>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									}
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</table>\n");
      out.write("\n");
      out.write("\t\t<br>\n");
      out.write("\n");
      out.write("     </div>\n");
      out.write("   \n");
      out.write("\t</form>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
