/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.26
 * Generated at: 2015-07-05 23:58:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.AirTraffic.Team2.Models.AirportBean;
import com.AirTraffic.Team2.Models.FlightBean;
import java.util.List;
import java.util.ArrayList;
import com.AirTraffic.Team2.Servlets.SearchFlightServlet;

public final class SearchFlight_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      com.AirTraffic.Team2.Models.FlightBean searchFlight = null;
      searchFlight = (com.AirTraffic.Team2.Models.FlightBean) _jspx_page_context.getAttribute("searchFlight", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (searchFlight == null){
        searchFlight = new com.AirTraffic.Team2.Models.FlightBean();
        _jspx_page_context.setAttribute("searchFlight", searchFlight, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<link\n");
      out.write("\thref=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/ui-lightness/jquery-ui.css\"\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<script\n");
      out.write("\tsrc=\"http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("$(document).ready(function() {\n");
      out.write("\t$(\"#departureDate\").datepicker({\n");
      out.write("\t\tdateFormat : \"yy-mm-dd\"\n");
      out.write("\t});\t\t\n");
      out.write("\t$(\"#arrivalDate\").datepicker({\n");
      out.write("\t\tdateFormat : \"yy-mm-dd\"\n");
      out.write("\t});\t\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<title>Flights Information</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<a href=\"index.html\">Home Page</a>\n");
      out.write("\t<h1 align=\"center\">Flight details</h1>\n");
      out.write("\t<form method=post action=\"searchFlight\">\n");
      out.write("\n");
      out.write("\t\t<table width=\"600\" height=\"300\" align=center cellspacing=0 border=\"0\"\n");
      out.write("\t\tcellpadding=0>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td>\n");
      out.write("\t\t\t\t<fieldset id=\"fieldhead\">\n");
      out.write("\t\t\t\t\t<legend>Flights Information</legend>\n");
      out.write("\t\t\t\t\t<BR>\n");
      out.write("\t\t\t\t\t<table align=center cellspacing=1 cellpadding=3>\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<div align=\"center\">\n");
      out.write("\t\t\t\t\t\t\t\t<table border=\"1\" cellpadding=\"5\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<caption>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h2>List of flights</h2>\n");
      out.write("\t\t\t\t\t\t\t\t\t</caption>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										if (request.getAttribute("error") != null) {
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>No Flights Found</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(request.getAttribute("error"));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										} else {
											if((request.getAttribute("flights")!=null && !(request.getAttribute("flights")=="")))
											{
											List<FlightBean> flightList = (ArrayList<FlightBean>) request
													.getAttribute("flights");
																						
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Flight ID</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Departure Time</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Arrival Time</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Departure Airport</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Arrival airport</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Departure Date</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Arrival Date</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Book Flight</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									
										
											for (int i = 0; i < flightList.size(); i++) {
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(flightList.get(i).getFlight_Id());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(flightList.get(i).getFlight_scheduled_departure_time());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(flightList.get(i).getFlight_scheduled_arrival_time());
      out.write("</td>\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(flightList.get(i).getFlightSegmentBean().getOriginAirport().getAirport_iata());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(flightList.get(i).getFlightSegmentBean().getDestinationAirport().getAirport_iata());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(flightList.get(i).getDepartureDate());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(flightList.get(i).getArrivalDate());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><a\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"booking?flightId=");
      out.print(flightList.get(i).getFlight_Id());
      out.write("\">Book Flight</a></td>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									session.setAttribute("flight", flightList);
									}
									
								}								
									
									
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t</table>\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t</table>\n");
      out.write("\t");

										if (request.getAttribute("error") != null) {
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>No Airport Found</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(request.getAttribute("error"));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										} else {	  
	    List<AirportBean> airportIataList = (ArrayList<AirportBean>) request
		.getAttribute("allIata");							
		
      out.write("\n");
      out.write("\n");
      out.write("\t\t<div align=\"center\">\n");
      out.write("\t\t\tDeparture Airport<select name=\"departureAirportDdl\">\n");
      out.write("\t\t\t\t");
 for (int i = 0; i < airportIataList.size(); i++) {	 
      out.write("\t\t\n");
      out.write("\t\t\t\t<option value=\"");
      out.print(airportIataList.get(i).getAirport_iata());
      out.write('"');
      out.write('>');
      out.print(airportIataList.get(i).getAirport_iata());
      out.write("</option>\n");
      out.write("\t\t\t\t");
}
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</select> \n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tArrival Airport<select name=\"arrivalAirportDdl\">\t\t\n");
      out.write("\t\t\t");
 for (int i = 0; i < airportIataList.size(); i++) {	 
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<option value=\"");
      out.print(airportIataList.get(i).getAirport_iata());
      out.write('"');
      out.write('>');
      out.print(airportIataList.get(i).getAirport_iata());
      out.write("</option>\n");
      out.write("\t\t\t\t");
}
				
				}
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</select> \n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<br> <br> \n");
      out.write("\t\t\t<label >Deaprture Date</label> <input\n");
      out.write("\t\t\t\ttype=\"text\" id=\"departureDate\" name=\"departureDate\"> <br> \n");
      out.write("\t\t\t<label >Arrival Date</label> <input\n");
      out.write("\t\t\t\ttype=\"text\" id=\"arrivalDate\" name=\"arrivalDate\"> <br> \n");
      out.write("\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Submit\">\n");
      out.write("\t\t</div>\n");
      out.write("\t</form>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
